repos:
  - repo: local
    hooks:
      - id: autoodocs
        name: autoodocs
        entry: bash -c '[ "$(git branch --show-current)" = "pages" ] && lua autodocs.lua . readme.md || true'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: autoosite
        name: autoosite
        entry: bash -c '[ "$(git branch --show-current)" = "pages" ] && lua mdtohtml.lua readme.md || true'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]