repos:
  - repo: local
    hooks:
      - id: autoodocs
        name: autoodocs
        entry: bash -c 'luajit build.lua && git add docs/'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
