repos:
  - repo: local
    hooks:
      - id: autodocs
        name: autodocs
        entry: bash -c 'lua build.lua && git add docs/'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
